security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/(login|register)
      stateless: true
      security: false

    main:
      pattern: ^/api
      provider: app_user_provider
      stateless: true
      jwt:
        authenticator: lexik_jwt_authentication.security.jwt_authenticator
      logout:
        path: app_logout

  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/users, roles: ROLE_ADMIN }
    - { path: ^/api/empresas, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
    - { path: ^/api/socios, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
